modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/obsidian_extension/issues"
[[mods]]
    modId="obsidian_extension" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Obsidian Extension" #mandatory
    #updateJSONURL="http://myurl.me/" #optional
    #displayURL="http://example.com/" #optional
    logoFile="obsidian_extension.png" #optional
    #credits="Thanks for this example mod goes to Java" #optional
    authors="justAm0dd3r"
    description='''This mod adds (crying) obsidian stairs, slabs, walls, ...'''

[[dependencies.obsidian_extension]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.obsidian_extension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
